function A = A_Arms(in1,in2)
%A_Arms
%    A = A_Arms(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:47

I1 = in2(3,:);
I2 = in2(4,:);
Ir = in2(5,:);
N = in2(6,:);
l_AB = in2(10,:);
l_A_m1 = in2(7,:);
l_B_m2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(2,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = N.^2;
t4 = l_B_m2.^2;
t5 = Ir.*N;
t6 = Ir.*t3;
t7 = m2.*t4;
t8 = l_AB.*l_B_m2.*m2.*t2;
t9 = I2+t5+t7+t8;
A = reshape([I1+I2+Ir+t6+t7+t8.*2.0+l_AB.^2.*m2+l_A_m1.^2.*m1,t9,t9,I2+t6+t7],[2,2]);
