function Corr_Joint_Sp = Corr_Arms(in1,in2)
%Corr_Arms
%    Corr_Joint_Sp = Corr_Arms(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:49

dth1 = in1(3,:);
dth2 = in1(4,:);
l_AB = in2(10,:);
l_B_m2 = in2(8,:);
m2 = in2(2,:);
th2 = in1(2,:);
t2 = sin(th2);
Corr_Joint_Sp = [-dth2.*l_AB.*l_B_m2.*m2.*t2.*(dth1.*2.0+dth2);dth1.^2.*l_AB.*l_B_m2.*m2.*t2];
