function E = energy_Arms(in1,in2)
%energy_Arms
%    E = energy_Arms(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:48

I1 = in2(3,:);
I2 = in2(4,:);
Ir = in2(5,:);
N = in2(6,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in2(12,:);
l_AB = in2(10,:);
l_A_m1 = in2(7,:);
l_B_m2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th2);
t3 = sin(th1);
t4 = N.^2;
t5 = dth1.^2;
t6 = dth2.^2;
t7 = l_B_m2.^2;
E = (I1.*t5)./2.0+(I2.*t5)./2.0+(I2.*t6)./2.0+(Ir.*t5)./2.0+(l_AB.^2.*m2.*t5)./2.0+(l_A_m1.^2.*m1.*t5)./2.0+g.*m2.*(l_AB.*t3+l_B_m2.*sin(th1+th2))+I2.*dth1.*dth2+(Ir.*t4.*t5)./2.0+(Ir.*t4.*t6)./2.0+(m2.*t5.*t7)./2.0+(m2.*t6.*t7)./2.0+dth1.*dth2.*m2.*t7+g.*l_A_m1.*m1.*t3+Ir.*N.*dth1.*dth2+l_AB.*l_B_m2.*m2.*t2.*t5+dth1.*dth2.*l_AB.*l_B_m2.*m2.*t2;
