function Grav_Joint_Sp = Grav_Arms(in1,in2)
%Grav_Arms
%    Grav_Joint_Sp = Grav_Arms(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:48

g = in2(12,:);
l_AB = in2(10,:);
l_A_m1 = in2(7,:);
l_B_m2 = in2(8,:);
m1 = in2(1,:);
m2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = th1+th2;
t4 = cos(t3);
Grav_Joint_Sp = [g.*m2.*(l_AB.*t2+l_B_m2.*t4)+g.*l_A_m1.*m1.*t2;g.*l_B_m2.*m2.*t4];
