function J = jacobian_Endeffector(in1,in2)
%jacobian_Endeffector
%    J = jacobian_Endeffector(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:48

l_AB = in2(10,:);
l_BC = in2(11,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l_BC.*t3;
t6 = l_BC.*t4;
t7 = -t6;
J = reshape([t7-l_AB.*sin(th1),t5+l_AB.*cos(th1),t7,t5],[2,2]);
