function keypoints = keypoints_Arms(in1,in2)
%keypoints_Arms
%    KEYPOINTS = keypoints_Arms(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:49

l_AB = in2(10,:);
l_BC = in2(11,:);
l_OA = in2(9,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t9 = -l_OA;
t5 = l_AB.*t2;
t6 = cos(t4);
t7 = l_AB.*t3;
t8 = sin(t4);
t10 = l_BC.*t6;
t11 = l_BC.*t8;
t12 = -t5;
t13 = t7+t11;
keypoints = reshape([l_OA,0.0,l_OA+t5,t7,l_OA+t5+t10,t13,t9,0.0,t9+t12,t7,t9-t10+t12,t13],[2,6]);
