function rEnd = position_Endeffector(in1,in2)
%position_Endeffector
%    rEnd = position_Endeffector(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:48

l_AB = in2(10,:);
l_BC = in2(11,:);
l_OA = in2(9,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
rEnd = [l_OA+l_BC.*cos(t2)+l_AB.*cos(th1);l_BC.*sin(t2)+l_AB.*sin(th1)];
