function drEnd = velocity_Endeffector(in1,in2)
%velocity_Endeffector
%    drEnd = velocity_Endeffector(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Dec-2023 11:37:48

dth1 = in1(3,:);
dth2 = in1(4,:);
l_AB = in2(10,:);
l_BC = in2(11,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
drEnd = [-dth1.*(l_BC.*t4+l_AB.*sin(th1))-dth2.*l_BC.*t4;dth1.*(l_BC.*t3+l_AB.*cos(th1))+dth2.*l_BC.*t3];
