function keypoints = keypoints_leg(in1,in2)
%keypoints_leg
%    KEYPOINTS = keypoints_Arms(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Dec-2023 17:32:15

l_AB = in2(10,:);
l_BC = in2(11,:);
l_OA = in2(9,:);


% %Right arm
th1 = -in1(1,:);
th2 = -in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l_AB.*t2;
t6 = l_AB.*t3;
keypoints = reshape([l_OA,0.0,l_OA+t5,t6,l_OA+t5+l_BC.*cos(t4),t6+l_BC.*sin(t4)],[2,3]);




%Left Arm 
% th1 = pi + in1(1,:);
% th2 = in1(2,:);
% t2 = cos(th1);
% t3 = sin(th1);
% t4 = th1+th2;
% t5 = l_AB.*t2;
% t6 = l_AB.*t3;
% keypoints = reshape([-l_OA,0.0,-l_OA+t5,t6,l_OA+t5+l_BC.*cos(t4),t6+l_BC.*sin(t4)],[2,3]);
% 


end